### ISSUE TITLE
npm start fails: TypeError: Buffer.alloc is not a function

### ISSUE THREAD

**Issue by dvdmuckle** [sabbatinifrancois/Freemaill_Project#1]
Currently trying to test this project after hearing about it at CCSCNE, trying to run it in Docker fails with this error using the `google/nodejs:latest` image.

```
/app/node_modules/pg/lib/connection.js:290
var emptyBuffer = Buffer.alloc(0)
                         ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (/app/node_modules/pg/lib/connection.js:290:26)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/app/node_modules/pg/lib/client.js:19:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```
This is when it tries to run the `bin/www` script.

**Comment by dvdmuckle** [comment]
Issues was an old version of `node`, this is resolved with using the `node:latest` image.
